### ISSUE TITLE
cannot install plugin

### ISSUE THREAD

**Issue by ullasmohan** [StephenForte/Stripe-Cordova#3]
Hi..

When i try to install the plugin through CLI ; 

cordova plugin add https://github.com/Telerik-Verified-Plugins/Stripe --variable API_KEY="my secret key"

It always return an error like ;

Fetching plugin "https://github.com/Telerik-Verified-Plugins/Stripe" via git clo
ne
Error: Command failed: fatal: could not create work tree dir 'C:\Users\ULLAS~1.F
TS\AppData\Local\Temp\plugman\git\1425293963660'.: No such file or directory

```
at ChildProcess.exithandler (child_process.js:637:15)
at ChildProcess.EventEmitter.emit (events.js:98:17)
at maybeClose (child_process.js:743:16)
at Socket.<anonymous> (child_process.js:956:11)
at Socket.EventEmitter.emit (events.js:95:17)
at Pipe.close (net.js:465:12)
```

**Comment by StephenForte** [comment]
Hi there:

This looks like a Git bug on Windows, updating Git could help according to
this SO issue:
http://stackoverflow.com/questions/23121382/cant-install-cordova-plugins-from-git-on-cli

**Comment by ullasmohan** [comment]
Thank you ! Its working :-)

I have another doubt ; 
How can i create subscription plans?
I Tried like 

stripe.plans.create({
  amount: 2000,
  interval: "month",
  name: "Amazing Gold Plan",
  currency: "usd",
  id: "gold"
}, function(plan) {
  alert(JSON.stringify(plan));
});

but its not working !
